config/routes.rb
Rails.application.routes.draw do
  get "dogs/index"
  root "dogs#index"
  get "about", to: "static_pages#about"
  get "home", to: "dogs#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :breeds, only: :show
  resources :dogs, only: :show do
    collection do
      get "search_results"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

    def self.ransackable_attributes(auth_object = nil)
    [ "created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at" ]
    end
end

app/models/adoption.rb
class Adoption < ApplicationRecord
  belongs_to :dog
  belongs_to :user

  validates :adoption_date, presence: true

  def self.ransackable_attributes(auth_object = nil)
    [ "adoption_date", "created_at", "dog_id", "id", "updated_at", "user_id" ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :dogs

  validates :name, presence: true

  def self.ransackable_associations(auth_object = nil)
    [ "dogs" ]
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "created_at", "id", "id_value", "name", "updated_at" ]
  end
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :breed

  has_many :adoptions
  has_many :users, through: :adoptions

  validates :name, :gender, presence: true
  validates :age, numericality: { only_integer: true }

  def self.ransackable_attributes(auth_object = nil)
    [ "age", "breed_id", "created_at", "description", "gender", "id", "id_value", "image_url", "name", "updated_at" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "adoptions", "breed", "users" ]
  end

  Dog.page(1).per(9)
end

app/models/user.rb
class User < ApplicationRecord
  has_many :adoptions
  has_many :dogs, through: :adoptions

  validates :name, :address, :city, :province, presence: true
  validates :phone_number, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.page(params[:page]).per(9)
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def search_results
    @query = params[:query]
    @dogs = Dog.where("name LIKE ?", "%#{@query}%")
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/breeds/index.html.erb
<h3 class="title is-4">All Dog Breeds</h3>

<p>
  <% @breeds.each do |breed| %>
    <%= link_to breed.name, breed, class: 'button is-link' %>
  <% end %>
</p>

app/views/breeds/show.html.erb
<h3 class="title is-4"><%= @breed.name %></h3>

<h4 class="subtitle is-5">Dogs of this breed</h4>

<div class="columns is-multiline">
  <%= render partial: 'dogs/dog',
            collection: @breed.dogs,
            locals: { name_is_link: true } %>
</div>

app/views/dogs/_dog.html.erb
<div class="column is-one-third">
  <div class="card dog">
    <div class="card-content">
      <h1 class="title is-4">
        <% if name_is_link %>
          <%= link_to dog.name, dog %>
        <% else %>
          <%= dog.name %> -
          <% if dog.age < 2 %>
          <span class="">Puppy</span>
          <% elsif dog.age > 7 %>
            <span class="">Senior Dog</span>
          <% else %>
            <span class="">Adult Dog</span>
          <% end %>
        <% end %>
      </h1>
      <% if dog.image_url.present? %>
        <div class="card-image">
          <figure class="image is-4by3">
            <img src="<%= dog.image_url %>" alt="<%= dog.name %>">
          </figure>
        </div>
      <% end %>
      <ul>
        <li><strong>Breed:</strong> <%= dog.breed.name.capitalize %></li>
        <li><strong>Age:</strong> <%= dog.age %></li>
        <li><strong>Gender:</strong> <%= dog.gender %></li>
        <li><strong>About Me:</strong> <%= dog.description %></li>
      </ul>
    </div>
  </div>
</div>

app/views/dogs/index.html.erb
<h1 class="title has-text-centered">Our Dogs</h1>

<div class="columns is-multiline">
  <% @dogs.each do |dog| %>
    <div class="column is-one-third">
      <div class="card">
        <div class="card-image">
          <% if dog.image_url.present? %>
            <figure class="image is-4by3">
              <img src="<%= dog.image_url %>" alt="<%= dog.name %>">
            </figure>
          <% end %>
        </div>
        <div class="card-content">
          <h2 class="title is-4">
            <%= link_to dog.name, dog %> -
            <% if dog.age < 2 %>
              <span class="tag is-success">Puppy</span>
            <% elsif dog.age > 7 %>
              <span class="tag is-warning">Senior Dog</span>
            <% else %>
              <span class="tag is-primary">Adult Dog</span>
            <% end %>
          </h2>
          <ul>
            <li><strong>Breed:</strong> <%= dog.breed.name.capitalize %></li>
            <li><strong>Age:</strong> <%= dog.age %></li>
            <li><strong>Gender:</strong> <%= dog.gender %></li>
          </ul>
          <p><strong>About Me:</strong> <%= dog.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= paginate @dogs %>

app/views/dogs/search_results.html.erb
<p>
  Your search for '<%= @query %>' returned <%= pluralize(@dogs.size, 'result') %>.
</p>

<div class="columns is-multiline">
  <%= render partial: 'dog',
            collection: @dogs,
            locals: { name_is_link: true } %>
</div>

app/views/dogs/show.html.erb
<div class="columns">
  <%= render partial: 'dog',
            object: @dog,
            locals: { name_is_link: false } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Intro To Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <%# stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <nav>
      <ul>
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>

    <section class="section">
      <h1 class="title"><%= link_to 'Paw Pals', root_path %></h1>
      <h2 class="subtitle">We have dogs.</h2>
      <%= form_with(url: search_results_dogs_path, method: "get", local: true) do %>
        <%= label_tag(:query, "Search for:") %>
        <%= text_field_tag(:query) %>
        <%= submit_tag("Search") %>
      <% end %>
    </section>
    <section class="section">
      <%= yield %>
    </section>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>This intro project will be a mockup of an adoption website for dogs making use of the Dog API
  (found here: https://dog.ceo/dog-api/). Along with this API, I will be using the 'faker' ruby gem
  to generate more data as needed. The Dog API is structured within a JSON which can then be drilled
  down into to extract information such as the breed, any associated sub-breeds, an image of those breeds, etc.
  The database tables required will be as follows.</p>

<header>Dogs</header>
<ul>
  <li>Dog_id - Integer</li>
  <li>Name - String</li>
  <li>Age - Integer</li>
  <li>Gender - String</li>
  <li>Breed_id - Integer (FK to Breeds table)</li>
  <li>Description - Text</li>
  <li>Image_url - String</li>
  <li>Created_at - Datetime</li>
  <li>Updated_at - Datetime</li>
</ul>

<header>Breeds</header>
<ul>
  <li>Breed_id - Integer</li>
  <li>Name - String</li>
  <li>Created_at - Datetime</li>
  <li>Updated_at - Datetime</li>
</ul>

<header>Users</header>
<ul>
  <li>User_id - Integer</li>
  <li>Name - String</li>
  <li>Address - String</li>
  <li>City - String</li>
  <li>Province - String</li>
  <li>Phone_number - String</li>
  <li>Email - String</li>
  <li>Created_at - Datetime</li>
  <li>Updated_at - Datetime</li>
</ul>

<header>Adoptions</header>
<ul>
  <li>Adoption_id - Integer</li>
  <li>Dog_id - Integer (FK to Dogs)</li>
  <li>User_id - Integer (FK to Users)</li>
  <li>Adoption_date - Datetime</li>
  <li>Created_at - Datetime</li>
  <li>Updated_at - Datetime</li>
</ul>

<h3>Here is the ERD for the database.</h3>

<%= image_tag "rails_erd.png", alt: "Mountain" %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>